lmj12/WebProjectKR

- WebContent/jquery-3.3.1.js
> jQuery 파일 프로젝트에 포함

- WebContent/APItest/daumAddress.jsp
불러온 후 form 에 작성하고
최종 submit 으로 데이터를 넘기는 형태로 진행 예상
Co-Authored-By: jkpark512 <jkpark512@users.noreply.github.com>
> Daum API 불러다 쓰기 완성

- WebContent/Jbp/jbpMod.jsp
- WebContent/Jbp/jbpReg.jsp
- WebContent/js/jbpReg.js
아이디
1.숫자 먹도록 고침
2.글자수 제한 됨
3. 아이디 형태 부적합할때 가입 누르면 안되게 막아야함>완료
비밀번호
1.최초 형태 안내 필요.>완료
2.적합하지 않으면 ajax로 옆칸에 안내 >완료
3.비밀번호 형태 부적합할때 가입 누르면 안되게 막아야함.
>완료, 동일문자, 숫자 3연속사용도 방지, 영문, 숫자,특수문자2종이상혼용해 비밀번호 만들도록설정
비밀번호확인
1. 동작
2. 비밀번호랑 다른경우에 가입되는거 막아야함.>완료
전화번호
1. 글자수 제한 (9~11)>완료
2. 전화번호 형태 안내.>완료
3. 빈칸인채 넘길때 막아야함>완료.
회원정보 수정
1.가입시 형식 적절하지 않아도 가입되는거 막아야함.>완료
2. 전화번호 못받아옴.>> 수정하겠음
3. 비밀번호 수정시 문자없어도 들어감.>>jbpmod.js가 아닌 jbpReg.js로 연동되도록 설정해서 될 것
일단 밑에 2개뺴고 다 함.
> 구인자 회원가입 대폭 수정

- WebContent/schedule/schView.jsp
- build/classes/schedule/schedule.xml
- src/schedule/SchNextHd.java
- src/schedule/SchPrevHd.java
- src/schedule/ScheduleDBBean.java
- src/schedule/schedule.xml
> Next Prev수정완료

- WebContent/estimate/estimateForm.jsp
- WebContent/js/jbpReg.js
- WebContent/setting/setting.jsp
기존에 있던 erroralert펑션을 setting으로 옮기고 errorback 펑션을 추가했습니다.
상황에 따라 쓰시면 될것 같습니다.
> 사후평가 폼 시작 및 erroralert 및 errorback 메소드 위치 변경  lmj12 committed

- WebContent/Jbp/jbpLgnPro.jsp
- WebContent/Jbs/jbskLgnPro.jsp
- WebContent/mypage.jsp
- WebContent/team/jbpTeam.jsp
- WebContent/team/jbskTeam.jsp
- WebContent/team/teamReq.jsp
- WebContent/team/teamReqCk.jsp
- WebContent/team/teamView.jsp
- build/classes/team/team.xml
- src/member/jobseeker/JbskLgnHd.java
- src/member/jobseeker/JbskViewHd.java
- src/team/TeamDBBean.java
- src/team/TeamDataBean.java
- src/team/TeamExitHd.java
- src/team/TeamReqCk.java
- src/team/TeamReqHd.java
- src/team/team.xml
오후에 두어시간정도 더 하면 팀 작업 완료될듯 합니다.
> 팀 작업관련 코드들 및 구직자 로그인시 팀가져오는 기능 구현

- WebContent/admin/adminPage.jsp
- WebContent/js/jbskReg.js
> 구직자 및 관리자 페이지 수정

- WebContent/admin/adminPage.jsp
- build/classes/board/board.xml
- src/board/BoardDBBean.java
- src/board/BoardListHd.java
- src/board/board.xml
관리자 페이지 기능 4개중 3개 기능 작동하도록 수정.
> 관리자 페이지 수정

- WebContent/setting/navbar.jsp
navbar.jsp에 관리자 로그인시 관리자페이지 탭 추가
> navbar.jsp에 관리자 로그인시 관리자페이지 탭 추가

- WebContent/recruit/recView.jsp
아이디 같을 시 구직자여도 공고수정, 삭제할 수 있는것을 막아놨음
> 공고내용페이지 수정

- WebContent/admin/adminPage.jsp
- build/classes/member/jobprov/jobprov.xml
- build/classes/member/jobseeker/jobseeker.xml
- src/member/jobprov/JbpViewHd.java
- src/member/jobprov/JobProvDBBean.java
- src/member/jobprov/jobprov.xml
- src/member/jobseeker/JbskViewHd.java
- src/member/jobseeker/JobSeekerDBBean.java
- src/member/jobseeker/jobseeker.xml
관리자 공지 작성과 세부기능을 제외한 기본 기능은 완료
> 관리자 페이지 임시 완료

- WebContent/admin/adminPage.jsp
- src/member/jobprov/JbpDelHd.java
- src/member/jobprov/JobProvDBBean.java
- src/member/jobseeker/JbskDelHd.java
관리자가 구직자, 구인자 회원을 조회하고 삭제버튼을 통하여 회원삭제 가능
> 관리자 회원조회 및 삭제 추가

- WebContent/lgn.jsp
> 관리자 로그인 가능

- WebContent/iptCrr/iptCrr.jsp
조~금 수정했습니다. 코드는 번잡스러운데 수정하셔도 됩니다.
> iptCrr 수정. 이력서 1,2 를 남성, 여성으로 수정

- WebContent/rsmlist.jsp
> 이력서검색 기초작업

- WebContent/admin/adminPage.jsp
- WebContent/iptCrr/iptCrr.jsp
- src/recruit/RecDelHd.java
> iptCrr 사소한 수정

- WebContent/Jbs/jbskMod.jsp
> jbskMod / 구직자수정  수정

- WebContent/Jbs/jbskMod.jsp
- WebContent/Jbs/reg/jbskReg.jsp
- WebContent/js/jbpMod.js
- WebContent/js/jbpReg.js
- WebContent/js/jbskMod.js
- WebContent/js/jbskReg2.js
> 구직자 사진 미리보기 가능

- WebContent/admin/adminPage.jsp
- WebContent/board/notice.jsp
- WebContent/iptCrr/iptCrr.jsp
관리자 페이지 : 날짜 정상적으로 보이게 수정
공지 페이지 : 테이블 수정
이력서 페이지 : 이력서 사진 보이게 설정(추후 수정해야)
> 관리자 페이지, 공지 페이지, 이력서 페이지

- WebContent/Jbs/reg/jbskReg.jsp
> 구직자 회원가입 수정

- WebContent/board/boardWrt.jsp
> 구직자 신고 글쓰기

- WebContent/schedule/calander.jsp
- src/board/BoardListHd.java
> 구직자 신고게시판 시간 수정 / 테스트용 ALERT 제거

- WebContent/board/boardMod.jsp
> 글수정 수정버튼 삭제

- WebContent/rsmDetail.jsp
> rmsDetail 사진 올리기
